[supervisord]
nodaemon=true
user=root

[program:nginx]
command=/usr/sbin/nginx -g 'daemon off;'
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true

[program:uvicorn]
command=uvicorn backend.main:app --host 127.0.0.1 --port 8000
directory=/app
environment=PYTHONPATH="/app",PYTHONUNBUFFERED="1"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
