name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Main  # Specify the environment

    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image for client
      uses: docker/build-push-action@v2
      with:
        context: ./client
        push: true
        tags: parmati/spotifyproject-frontend:latest

    - name: Build and push Docker image for spotify_project
      uses: docker/build-push-action@v2
      with:
        context: ./spotify_project
        push: true
        tags: parmati/spotifyproject-api:latest
